# Generated by Django 2.2.4 on 2020-12-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beltApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='network',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='show',
            name='title',
        ),
    ]
